### ISSUE TITLE
List pagination

### ISSUE THREAD

**Issue by S1mplyD** [S1mplyD/RecipeBotReborn#23]
Category list has to many entries to be displayed, add pagination system to improve UX

**Comment by Rex-82** [comment]
I was thinking alternatively to condense the list by merging redundant entries. 

Eg:
89) Salad Dressing Recipes
90) Salads
91) Salmon
92) Salmon Salad Recipes

Would become:
89) Salad
90) Salmon


I'll try to thinker a bit and see which one is more viable.

**Comment by S1mplyD** [comment]
The pagination system is easier to implement, but your solution is clearly better. I approve your way

**Comment by Rex-82** [comment]
After tinkering a bit with the current list i came to these conclusions:
### Cleaned list
The cleaned list, by following a method similar to the one explained above, gives a new list of `98 items`. This is not enough to constitute a "category list" since it **spans too wide** and is therefore **not useful for the purpose**.
### Pagination
Pagination could help in some regard, making the broad list more "organized" but **failing to account for the number of elements**.
### Counting
Another approach could involve **counting recipes entries** for each category and **show the items by occurrence** (all of them or an arbitrary fraction of the list). This could be db intensive if done for each `/list` command and should be performed at startup.
<hr>

As the recipes db grows this will become an issue we should account for more and more as the category field is not so strictly set up as on the other source we used.

<hr>


The "last resort" would be to populate the list manually with the aid of said solutions (one of the above or a combination of them).

**Comment by S1mplyD** [comment]
What if we combine cleaned list and pagination? We could have 4 pages of 25 categories each. To me it seems the "best" worst solution
